spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsxdb?useSSL=false&createDatabaseIfNotExist=true
    username: user_db
    password: pass_db
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update